### ISSUE TITLE
Error C4800 when building (Winx64, UE4.18)

### ISSUE THREAD

**Issue by ghost** [Phyronnaz/Voxel#11]
Hey everyone! I added the plugin, but when I attempted to build again, I received these errors. Can anyone provide any insight?

2>...\Plugins\Voxel\Source\Voxel\Private\VoxelRender\Private\CollisionMeshHandler.cpp(52): 
error C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
2>...\Plugins\Voxel\Source\Voxel\Private\VoxelRender\Private\CollisionMeshHandler.cpp(246): error C4800: 'int32': forcing value to bool 'true' or 'false' (performance warning)

**Comment by Phyronnaz** [comment]
As written in the wiki:
You can either fix all the errors manually by adding `#pragma warning( disable : 4800 )` at the beginning of the files with errors, or remove VS 2015 and install VS 2017.

**Comment by ghost** [comment]
Never mind. I seem to have resolved it by removing the plugin content and disabling the plugin from notepad, then restarting the process. Sorry for the confusion! This is an amazing project!

Edit: Sorry I must have missed that. I also didn't see your response until just now. Thank you for the assistance!
